### ISSUE TITLE
Registry: Add setActive function to ReleaseManager

### ISSUE THREAD

**Issue by matthiaszimmermann** [etherisc/gif-next#331]
once a GIF release has been deployed and registered with the ReleaseManger it is not possible to (temporarily) (de)activate the release.

add a setActive(VersionPart majorVersion) function that can be used to (de)activate deployed GIF releases
- restricted to GIF_ADMIN_ROLE
- if a release is de-activated any attempt to mint nfts for that release must revert (= kill switch for a complete release)
- intended as a last resort alternative to allow time to analyze fatal/critical bugs within that release 
- individual GIF services might then be adapted/fixed accordingly
- once such critical/fatal bugs have been fixed, the release in question may be activated again

**Comment by doerfli** [comment]
done.
