### ISSUE TITLE
ClaimIds unique to each product / chain

### ISSUE THREAD

**Issue by rapidddenis** [etherisc/gif-next#371]
Given claimId it is easy to derive product and chainId where this product deployed

**Comment by doerfli** [comment]
The claimis is only unique in combination with the policynftid, but then its unique over all chains as the nftid contains the chainid.

**Comment by rapidddenis** [comment]
but it is not unique for product?

**Comment by doerfli** [comment]
its connected to the application/policy nft id (see https://github.com/etherisc/gif-next/blob/experiment/ignition/contracts/product/ClaimService.sol#L81). the claimid is an incremented integer stored per policy (in the policydata). 
each nftid encodes the chainid in its number, so its guaranteed to be unique per chain.

**Comment by rapidddenis** [comment]
my bad,  question resolved then
