### ISSUE TITLE
Update solidity to version of openzeppelin

### ISSUE THREAD

**Issue by doerfli** [etherisc/gif-next#386]
OpenZeppelin currently uses 0.8.24 and cancun evm compatibility

**Comment by rapidddenis** [comment]
each file in release. 5.0.2 goes with `pragma solidity ^0.8.20`

**Comment by doerfli** [comment]
yes, but
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/foundry.toml#L2
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/hardhat.config.js#L21

**Comment by doerfli** [comment]
use 0.8.26 but keep pragma to ^0.8.20
