### ISSUE TITLE
Checks-effects-interactions adhernce within PolicyService might still violate in upper-level contracts

### ISSUE THREAD

**Issue by marcoatpaladin** [etherisc/gif-next#515]
https://github.com/etherisc/gif-next/blob/401ed87f073d09aaa7643a6a9fa76a9f195a6d82/contracts/product/PolicyService.sol#L236

Even though functions like the above are written in CEI, they might not be when they are called from an upper level contract (eg. the Product).

We recommend Etherisc to be careful with any such interactions, the above being a uttermost dangerous one (others are often a bit less dangerous), and ensure that where these functions are being used (eg. within the product), that these interactions occur last.

- [x] #522

**Comment by doerfli** [comment]
See #471 for call stacks to token transfers

**Comment by doerfli** [comment]
made it more flexible for components to support custom process flows by splitting policy creation and token collection as well as splitting bundle creation and initial staking into two separate calls.
