### ISSUE TITLE
CreatePolicy allows to lock collateral but policy is never activated/paid

### ISSUE THREAD

**Issue by doerfli** [etherisc/gif-next#532]
when `createPolicy` is called with activatedAt = 0 or in the very future, this will lock the collateral and the policy could never be activated and no premium paid. Expiration is not possible on policies that have never been activated, so this will lock up the pool indefinitely.

**Comment by doerfli** [comment]
# Analysis

## Activated now but never paid ✅ 

- createPolicy(nft, 0)

collateral is locked and will be released after policy expired. no premium collected, but no long term collateral lock

## Activated a long time in the future and never paid ❌ 

- createPolicy(nft, 999999999999999999)

collateral is locked and never released

## Activated now and paid ✅ 

- createPolicy(nft, 0)
- collectPremium(nft, 0)

collateral is locked and will be released after policy expired, premium is collected and available to pool owner as income

## Activated a long time on the future and paid 🟡 ❌ 

- createPolicy(nft, 999999999999999999)
- collectPremium(nft, 999999999999999999)

collateral is locked and will never be released, premium is collected and available to pool owner as income

**Comment by doerfli** [comment]
decision: add an `adjustActivateAt` function that allows to change the activatedAt date. Ensure that activatedAt is not >= expiredAt.

**Comment by rapidddenis** [comment]
Does "activation in the future" is mandatory at framework level?
